### ISSUE TITLE
Cannot access our own database

### ISSUE THREAD

**Issue by bradley101** [abhiccc5/bridge#1]
I want to access my own database. I have a large set if excel files properly organized by tables. I want to extract data to my own db server.

**Comment by getabhishekified** [comment]
yes, this is exactly what the software does, lets you access any database
if you have its hostname, username, password and database name
..

**Comment by getabhishekified** [comment]
are you getting any errors while doing this job ?
read the instructions mentioned in the big-box properly !

**Comment by bradley101** [comment]
I don't know PHP 😄 , and how to write it.

**Comment by getabhishekified** [comment]
no , u need not know php for this, just select excel file and enter your db details and push the button , you are done

**Comment by getabhishekified** [comment]
as you open the software , instructions are shown , read them first ; just a few points
